In [2]:
import numpy as np

In [1]:
from scipy.linalg import expm

In [5]:
np.cross([1,0,0],[0,1,0])

array([0, 0, 1])

# Main Code

In [8]:
import numpy as np

# cross = np.cross

# 18th April, 2018
# Related Matlab Code: Desktop\mat-workspace\MatlabCode-UR

w=[[0, 0, 1], [1, 0, 0], [1, 0, 0], [1, 0, 0], [0, 0, 1], [0, 1, 0]];
pj=[[0, 0, 0], [0, 0, 0], [0, 0, 5], [0, 4, 5], [0, 4, 7], [0, 5, 7]];

In [51]:
w = np.array(w)
pj = np.array(pj)

In [15]:
DoF = 6

In [18]:
ksai = []
for i in range(DoF):
    ksai.append( np.array([cross(-w[i],q[i]), w[i]]).reshape(-1) )

In [19]:
# ksai

[array([0, 0, 0, 0, 0, 1]),
 array([0, 0, 0, 1, 0, 0]),
 array([0, 5, 0, 1, 0, 0]),
 array([ 0,  5, -4,  1,  0,  0]),
 array([4, 0, 0, 0, 0, 1]),
 array([-7,  0,  0,  0,  1,  0])]

In [14]:
ksai_wan = [np.matrix([[0, -1, 0, 0],
[1, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0]]),

np.matrix([[0, 0, 0, 0],
[0, 0, -1, 0],
[0, 1, 0, 0],
[0, 0, 0, 0]]),

np.matrix([[0, 0, 0, 0],
[0, 0, -1, 5],
[0, 1, 0, 0],
[0, 0, 0, 0]]),

np.matrix([[0, 0, 0, 0],
[0, 0, -1, 5],
[0, 1, 0, -4],
[0, 0, 0, 0]]),

np.matrix([[0, -1, 0, 4],
[1, 0, 0, 0],
[0, 0, 0, 0],
[0, 0, 0, 0]]),

np.matrix([[0, 0, 1, -7],
[0, 0, 0, 0],
[-1, 0, 0, 0],
[0, 0, 0, 0]])]

# ksai_wan = np.array(ksai_wan)

In [9]:
tmp = np.concatenate( ( np.eye(3), np.array([pj[-1]]).T ), axis = 1 )

In [10]:
gst0 = np.concatenate( (tmp, [[0,0,0,1]]), axis = 0)

In [20]:
gst0 = np.matrix(gst0)

In [21]:
gst0

matrix([[ 1.,  0.,  0.,  0.],
        [ 0.,  1.,  0.,  5.],
        [ 0.,  0.,  1.,  7.],
        [ 0.,  0.,  0.,  1.]])

In [38]:
def gst(th):
    th = np.array(th)
    tmp = 1.0
    for i in range(6):
#         print( np.matrix(ksai_wan[i]*th[i]) )
#         print(expm( ksai_wan[i]*th[i] ))
        tmp *= expm( ksai_wan[i]*th[i] )

    return tmp*gst0

In [39]:
gst( [np.pi,0,0,0,0,np.pi] )

[[ 0.         -3.14159265  0.          0.        ]
 [ 3.14159265  0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]
 [ 0.          0.          0.          0.        ]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]]
[[  0.           0.           3.14159265 -21.99114858]
 [  0.           0.           0.           0.        ]
 [ -3.14159265   0.           0.           0.        ]
 [  0.           0.           0.           0.        ]]


matrix([[ 1.,  0.,  0.,  0.],
        [ 0., -1.,  0., -5.],
        [ 0.,  0., -1., -7.],
        [ 0.,  0.,  0.,  1.]])

In [30]:
theta=[2.733441446706662,0.574994187643745,-2.421370235196160,0.068983671367797,-2.681284089871026,-1.321166266591099];

In [31]:
gst(theta)

matrix([[ 0.20315085,  0.        ,  0.        ,  0.        ],
        [ 0.        , -0.51747757,  0.        , -2.58738786],
        [ 0.        ,  0.        , -0.15546291, -1.08824039],
        [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [40]:
gst( [1,0,0,0,0,0] )

[[ 0 -1  0  0]
 [ 1  0  0  0]
 [ 0  0  0  0]
 [ 0  0  0  0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


matrix([[ 0.54030231,  0.        ,  0.        ,  0.        ],
        [ 0.        ,  0.54030231,  0.        ,  2.70151153],
        [ 0.        ,  0.        ,  1.        ,  7.        ],
        [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [58]:
np.zeros(6)

array([ 0.,  0.,  0.,  0.,  0.,  0.])